@baseUrl = http://localhost:3000/api/v1

### Authentication

### SIGNUP
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name": "lucas",
    "email": "email@email.com",
    "password": "123456"
}

### LOGIN
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "lucas@lucas.com",
    "password": "123456"
}

### REFRESH TOKEN
POST {{baseUrl}}/auth/refresh HTTP/1.1
Content-Type: application/json

### LOGOUT
POST {{baseUrl}}/auth/logout HTTP/1.1
Content-Type: application/json

### Users

### List users
GET {{baseUrl}}/users?page=1&size=1 HTTP/1.1
Content-Type: application/json

### Get user
GET {{baseUrl}}/users/9398095a-10aa-4566-92a1-b2f0f7f817af HTTP/1.1
Content-Type: application/json

### Create user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "user test2",
    "email": "test2@test.com",
    "password": "123456",
    "queueIds": [119,120]
}
### RequisicaoEstoque Routes

### List requisicaoEstoque with pagination
GET {{baseUrl}}/requisicoes-estoque?page=1&size=10 HTTP/1.1
Content-Type: application/json

### List all requisicaoEstoque without pagination
GET {{baseUrl}}/requisicoes-estoque-all HTTP/1.1
Content-Type: application/json

### Get requisicaoEstoque by ID
GET {{baseUrl}}/requisicoes-estoque/1 HTTP/1.1
Content-Type: application/json

### Create requisicaoEstoque
POST {{baseUrl}}/requisicoes-estoque HTTP/1.1
Content-Type: application/json

{
    "dataRequisicao": "2024-02-12",
    "ordemProducao": "OP001",
    "valorTotal": 150.75,
    "obs": "Observação teste",
    "requisitante": {
        "id": 2
    },
    "equipamento": {
        "id": 2
    },
    "itens": [
        {
            "id": null,
            "quantidade": 2,
            "undEstoque": "LITRO",
            "valorUnitario": 50.25,
            "insumo": {
                "id": 3
            }
        }
    ]
}

### Update requisicaoEstoque
PUT {{baseUrl}}/requisicoes-estoque/14 HTTP/1.1
Content-Type: application/json

{
    "id": 14,
    "dataRequisicao": "2024-02-12T10:00:00.000Z",
    "ordemProducao": "OP001-updated",
    "valorTotal": 200.50,
    "obs": "Observação atualizada",
    "requisitante": {
        "id": 1
    },
    "equipamento": {
        "id": 1
    },
    "itens": [
        {
            "id": 33,
            "quantidade": 300,
            "undEstoque": "LITRO",
            "valorUnitario": 50.25,
            "insumo": {
                "id": 1
            },
            "id": 34,
            "quantidade": 300,
            "undEstoque": "LITRO",
            "valorUnitario": 50.25,
            "insumo": {
                "id": 1
            }
        }
    ]
}

### Delete requisicaoEstoque
DELETE {{baseUrl}}/requisicoes-estoque/13 HTTP/1.1
Content-Type: application/json
