services:
  postgres_prod:
    container_name: database_project_prod
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - app_network_prod
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  postgres_prod_data:

networks:
  app_network_prod:
    driver: bridge