name: printerp
services:
  postgres_test:
    container_name: database_printerp_test
    image: postgres:16.0-alpine3.18
    ports:
      - "5433:5432"
    env_file:
      - ../.env.test
    networks:
      - printerp_network_test
    volumes:
      - printerp_test_data:/var/lib/postgresql/data

volumes:
  printerp_test_data:

networks:
  printerp_network_test:
    driver: bridge