import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1740517069442 implements MigrationInterface {
    name = 'Default1740517069442'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "fk_insumos_on_categorias"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "fk_requisicoes_estoque_on_equipamentos"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "fk_requisicoes_estoque_on_requisitantes"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "fk_requisicoes_estoque_itens_on_insumos"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "fk_requisicoes_estoque_itens_on_requisicoes_estoque"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "token_version" character varying(255), "user_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."movimentos_estoque_undidade_enum" AS ENUM('AMPOLA', 'BALDE', 'BANDEJ', 'BARRA', 'BISNAG', 'BLOCO', 'BOBINA', 'BOMB', 'CAPS', 'CART', 'CENTO', 'CJ', 'CM', 'CM2', 'CX', 'CX2', 'CX3', 'CX5', 'CX10', 'CX15', 'CX20', 'CX25', 'CX50', 'CX100', 'DISP', 'DUZIA', 'EMBAL', 'FARDO', 'FOLHA', 'FRASCO', 'GALAO', 'GF', 'GRAMAS', 'JOGO', 'KG', 'KIT', 'LATA', 'LITRO', 'M', 'M2', 'M3', 'MILHEI', 'ML', 'MWH', 'PACOTE', 'PALETE', 'PARES', 'PC', 'POTE', 'K', 'RESMA', 'ROLO', 'SACO', 'SACOLA', 'TAMBOR', 'TANQUE', 'TON', 'TUBO', 'UNID', 'VASIL', 'VIDRO')`);
        await queryRunner.query(`CREATE TABLE "movimentos_estoque" ("id" SERIAL NOT NULL, "tipo" character varying(50) NOT NULL, "data" TIMESTAMP NOT NULL, "quantidade" numeric(10,2) NOT NULL, "valor_unitario" numeric(10,2) NOT NULL, "undidade" "public"."movimentos_estoque_undidade_enum" NOT NULL, "documento_origem" character varying(255) NOT NULL, "tipo_documento" character varying(50) NOT NULL, "regularizado" boolean NOT NULL DEFAULT false, "observacao" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" character varying(255), "armazem_origem_id" integer, "armazem_destino_id" integer, "insumo_id" integer, CONSTRAINT "PK_f0167ad29177850a7c4dc6d4606" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armazens" ("id" SERIAL NOT NULL, "nome" character varying(255) NOT NULL, "ativo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" character varying(255), CONSTRAINT "UQ_400d1bf5d06da8279326e57c4e8" UNIQUE ("nome"), CONSTRAINT "PK_395344d5289ccafcc9dfa1ac08a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "estoques" ("id" SERIAL NOT NULL, "quantidade" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" character varying(255), "armazem_id" integer, "insumo_id" integer, CONSTRAINT "PK_049cbdf51633449b22f020680d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("key" character varying(255) NOT NULL, "value" text NOT NULL, "user_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_c8639b7626fa94ba8265628f214" PRIMARY KEY ("key"))`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "total_entradas"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "total_saidas"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "categorias_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "requisitantes_id"`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "permite_estoque_negativo" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "categoria_id" integer`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "requisitante_id" integer`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "armazem_id" integer`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP CONSTRAINT "pk_categorias"`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD CONSTRAINT "PK_3886a26251605c571c6b4f861fe" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "pk_insumos"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "PK_b4e1b727a7b140e698e3a3dc7af" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "uc_insumos_descricao"`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med_auto" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "und_estoque"`);
        await queryRunner.query(`CREATE TYPE "public"."insumos_und_estoque_enum" AS ENUM('AMPOLA', 'BALDE', 'BANDEJ', 'BARRA', 'BISNAG', 'BLOCO', 'BOBINA', 'BOMB', 'CAPS', 'CART', 'CENTO', 'CJ', 'CM', 'CM2', 'CX', 'CX2', 'CX3', 'CX5', 'CX10', 'CX15', 'CX20', 'CX25', 'CX50', 'CX100', 'DISP', 'DUZIA', 'EMBAL', 'FARDO', 'FOLHA', 'FRASCO', 'GALAO', 'GF', 'GRAMAS', 'JOGO', 'KG', 'KIT', 'LATA', 'LITRO', 'M', 'M2', 'M3', 'MILHEI', 'ML', 'MWH', 'PACOTE', 'PALETE', 'PARES', 'PC', 'POTE', 'K', 'RESMA', 'ROLO', 'SACO', 'SACOLA', 'TAMBOR', 'TANQUE', 'TON', 'TUBO', 'UNID', 'VASIL', 'VIDRO')`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "und_estoque" "public"."insumos_und_estoque_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "estoque_minimo" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "estoque_minimo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP CONSTRAINT "pk_equipamentos"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD CONSTRAINT "PK_0db94e9eed96824cb4446343a86" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP CONSTRAINT "pk_requisitantes"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD CONSTRAINT "PK_217e259327009b9ee87821bc07e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "fone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "pk_requisicoes_estoque"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "PK_5ee11723bf79ec49cf429e372f5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "data_requisicao" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "valor_total" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "valor_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "equipamentos_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "equipamentos_id" integer`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "pk_requisicoes_estoque_itens"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "PK_d078291735274987d33366846a7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ALTER COLUMN "quantidade" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "unidade"`);
        await queryRunner.query(`CREATE TYPE "public"."requisicoes_estoque_itens_unidade_enum" AS ENUM('AMPOLA', 'BALDE', 'BANDEJ', 'BARRA', 'BISNAG', 'BLOCO', 'BOBINA', 'BOMB', 'CAPS', 'CART', 'CENTO', 'CJ', 'CM', 'CM2', 'CX', 'CX2', 'CX3', 'CX5', 'CX10', 'CX15', 'CX20', 'CX25', 'CX50', 'CX100', 'DISP', 'DUZIA', 'EMBAL', 'FARDO', 'FOLHA', 'FRASCO', 'GALAO', 'GF', 'GRAMAS', 'JOGO', 'KG', 'KIT', 'LATA', 'LITRO', 'M', 'M2', 'M3', 'MILHEI', 'ML', 'MWH', 'PACOTE', 'PALETE', 'PARES', 'PC', 'POTE', 'K', 'RESMA', 'ROLO', 'SACO', 'SACOLA', 'TAMBOR', 'TANQUE', 'TON', 'TUBO', 'UNID', 'VASIL', 'VIDRO')`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "unidade" "public"."requisicoes_estoque_itens_unidade_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ALTER COLUMN "valor_unitario" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "insumos_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "insumos_id" integer`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "requisicoes_estoque_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "requisicoes_estoque_id" integer`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" ADD CONSTRAINT "FK_263864180fa1722935b2c6a24fc" FOREIGN KEY ("armazem_origem_id") REFERENCES "armazens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" ADD CONSTRAINT "FK_90b151f8373e6a63f78698d28b0" FOREIGN KEY ("armazem_destino_id") REFERENCES "armazens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" ADD CONSTRAINT "FK_af99ea2738bb30e8892c1ff408e" FOREIGN KEY ("insumo_id") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estoques" ADD CONSTRAINT "FK_5615b9415c67026aef69c9e0af4" FOREIGN KEY ("armazem_id") REFERENCES "armazens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estoques" ADD CONSTRAINT "FK_0ecc351a100765a385b8277f44f" FOREIGN KEY ("insumo_id") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_998362c3f6fd2e8f4b19aa4d5da" FOREIGN KEY ("categoria_id") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "FK_0fab199ed6eaa484572b66c8f7e" FOREIGN KEY ("requisitante_id") REFERENCES "requisitantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "FK_a59a8c27123c1aaf89259da056c" FOREIGN KEY ("equipamentos_id") REFERENCES "equipamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "FK_d404274b3a61f65a7c0bc1d6ca9" FOREIGN KEY ("armazem_id") REFERENCES "armazens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "FK_2d011a3b06024eeaf2145c05cc9" FOREIGN KEY ("insumos_id") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "FK_221af3495763304b3a94e455cf1" FOREIGN KEY ("requisicoes_estoque_id") REFERENCES "requisicoes_estoque"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "FK_221af3495763304b3a94e455cf1"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "FK_2d011a3b06024eeaf2145c05cc9"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "FK_d404274b3a61f65a7c0bc1d6ca9"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "FK_a59a8c27123c1aaf89259da056c"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "FK_0fab199ed6eaa484572b66c8f7e"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_998362c3f6fd2e8f4b19aa4d5da"`);
        await queryRunner.query(`ALTER TABLE "estoques" DROP CONSTRAINT "FK_0ecc351a100765a385b8277f44f"`);
        await queryRunner.query(`ALTER TABLE "estoques" DROP CONSTRAINT "FK_5615b9415c67026aef69c9e0af4"`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" DROP CONSTRAINT "FK_af99ea2738bb30e8892c1ff408e"`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" DROP CONSTRAINT "FK_90b151f8373e6a63f78698d28b0"`);
        await queryRunner.query(`ALTER TABLE "movimentos_estoque" DROP CONSTRAINT "FK_263864180fa1722935b2c6a24fc"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "requisicoes_estoque_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "requisicoes_estoque_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "insumos_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "insumos_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ALTER COLUMN "valor_unitario" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "unidade"`);
        await queryRunner.query(`DROP TYPE "public"."requisicoes_estoque_itens_unidade_enum"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "unidade" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ALTER COLUMN "quantidade" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP CONSTRAINT "PK_d078291735274987d33366846a7"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "pk_requisicoes_estoque_itens" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "equipamentos_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "equipamentos_id" bigint`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "valor_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "valor_total" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ALTER COLUMN "data_requisicao" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP CONSTRAINT "PK_5ee11723bf79ec49cf429e372f5"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "pk_requisicoes_estoque" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ALTER COLUMN "fone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP CONSTRAINT "PK_217e259327009b9ee87821bc07e"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "requisitantes" ADD CONSTRAINT "pk_requisitantes" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP CONSTRAINT "PK_0db94e9eed96824cb4446343a86"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipamentos" ADD CONSTRAINT "pk_equipamentos" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "estoque_minimo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "estoque_minimo" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "und_estoque"`);
        await queryRunner.query(`DROP TYPE "public"."insumos_und_estoque_enum"`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "und_estoque" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med_auto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "insumos" ALTER COLUMN "valor_unt_med" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "uc_insumos_descricao" UNIQUE ("descricao")`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "PK_b4e1b727a7b140e698e3a3dc7af"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "pk_insumos" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "categorias" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP CONSTRAINT "PK_3886a26251605c571c6b4f861fe"`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categorias" ADD CONSTRAINT "pk_categorias" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "armazem_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "requisitante_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "requisitantes" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "equipamentos" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "categoria_id"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP COLUMN "permite_estoque_negativo"`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "categorias" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD "requisitantes_id" bigint`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "categorias_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "total_saidas" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD "total_entradas" numeric NOT NULL`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "estoques"`);
        await queryRunner.query(`DROP TABLE "armazens"`);
        await queryRunner.query(`DROP TABLE "movimentos_estoque"`);
        await queryRunner.query(`DROP TYPE "public"."movimentos_estoque_undidade_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "fk_requisicoes_estoque_itens_on_requisicoes_estoque" FOREIGN KEY ("requisicoes_estoque_id") REFERENCES "requisicoes_estoque"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque_itens" ADD CONSTRAINT "fk_requisicoes_estoque_itens_on_insumos" FOREIGN KEY ("insumos_id") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "fk_requisicoes_estoque_on_requisitantes" FOREIGN KEY ("requisitantes_id") REFERENCES "requisitantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisicoes_estoque" ADD CONSTRAINT "fk_requisicoes_estoque_on_equipamentos" FOREIGN KEY ("equipamentos_id") REFERENCES "equipamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "fk_insumos_on_categorias" FOREIGN KEY ("categorias_id") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
