export const profiles = [
  {
    value: "user",
    label: "usuário",
  },
  {
    value: "admin",
    label: "administrador",
  },
];

export const unidades = [
  { value: "AMPOLA", label: "Ampola" },
  { value: "BALDE", label: "Balde" },
  { value: "BANDEJ", label: "Bandeja" },
  { value: "BARRA", label: "Barra" },
  { value: "BISNAG", label: "Bisnaga" },
  { value: "BLOCO", label: "Bloco" },
  { value: "BOBINA", label: "Bobina" },
  { value: "BOMB", label: "Bomba" },
  { value: "CAPS", label: "Cápsula" },
  { value: "CART", label: "Cartela" },
  { value: "CENTO", label: "Cento" },
  { value: "CJ", label: "Conjunto" },
  { value: "CM", label: "Centímetro" },
  { value: "CM2", label: "Centímetro quadrado" },
  { value: "CX", label: "Caixa" },
  { value: "CX2", label: "Caixa com 2 unidades" },
  { value: "CX3", label: "Caixa com 3 unidades" },
  { value: "CX5", label: "Caixa com 5 unidades" },
  { value: "CX10", label: "Caixa com 10 unidades" },
  { value: "CX15", label: "Caixa com 15 unidades" },
  { value: "CX20", label: "Caixa com 20 unidades" },
  { value: "CX25", label: "Caixa com 25 unidades" },
  { value: "CX50", label: "Caixa com 50 unidades" },
  { value: "CX100", label: "Caixa com 100 unidades" },
  { value: "DISP", label: "Display" },
  { value: "DUZIA", label: "Dúzia" },
  { value: "EMBAL", label: "Embalagem" },
  { value: "FARDO", label: "Fardo" },
  { value: "FOLHA", label: "Folha" },
  { value: "FRASCO", label: "Frasco" },
  { value: "GALAO", label: "Galão" },
  { value: "GF", label: "Garrafa" },
  { value: "GRAMAS", label: "Gramas" },
  { value: "JOGO", label: "Jogo" },
  { value: "KG", label: "Quilograma" },
  { value: "KIT", label: "Kit" },
  { value: "LATA", label: "Lata" },
  { value: "LITRO", label: "Litro" },
  { value: "M", label: "Metro" },
  { value: "M2", label: "Metro quadrado" },
  { value: "M3", label: "Metro cúbico" },
  { value: "MILHEI", label: "Milheiro" },
  { value: "ML", label: "Mililitro" },
  { value: "MWH", label: "Megawatt-hora" },
  { value: "PACOTE", label: "Pacote" },
  { value: "PALETE", label: "Palete" },
  { value: "PARES", label: "Pares" },
  { value: "PC", label: "Peça" },
  { value: "POTE", label: "Pote" },
  { value: "K", label: "Quilate" },
  { value: "RESMA", label: "Resma" },
  { value: "ROLO", label: "Rolo" },
  { value: "SACO", label: "Saco" },
  { value: "SACOLA", label: "Sacola" },
  { value: "TAMBOR", label: "Tambor" },
  { value: "TANQUE", label: "Tanque" },
  { value: "TON", label: "Tonelada" },
  { value: "TUBO", label: "Tubo" },
  { value: "UNID", label: "Unidade" },
  { value: "VASIL", label: "Vasilhame" },
  { value: "VIDRO", label: "Vidro" },
];
